/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PanelPreview: typeof import('./components/PanelPreview.vue')['default']
    PanelProps: typeof import('./components/PanelProps.vue')['default']
    PanelVue: typeof import('./components/PanelVue.vue')['default']
    Playground: typeof import('./components/Playground.vue')['default']
  }
}
