name: gh-action

on:
  push:
    branches:
      - vite-vue3
    # tags:
    #   - v*
  workflow_dispatch:

jobs:
  ci_job:
    name: CI Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16 # ${{ matrix.node }}
          cache: npm

      - uses: lvjiaxuan/release-deploy-publish-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          enableReleaseBoolean: false
          enableDeployBoolean: false

      - name: NPM Publish
        run: |
          npm ci
          npm run build:lib
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
