name: 'ci'

on:
  push:
    branches:
      - vite-vue3
    # tags:
    #   - v*
  workflow_dispatch:

jobs:
  deploy_job:
    name: Deploy Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16 # ${{ matrix.node }}
          cache: 'npm'

      - uses: lvjiaxuan/release-deploy-publish-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          debug: true
          enableDeployBoolean: true
          deployScript: npm run ci"
