name: 'ci'

on:
  push:
    branches:
      - vite-vue3
    # tags:
    #   - v*
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  deploy_job:
    name: Deploy Job
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [ '12', '14', '16' ]
    steps:
      - uses: actions/checkout@v3
        # with:
        #   repository: 'lvjiaxuan/vue-number-roll'

      - uses: actions/setup-node@v2
        with:
          node-version: 16 # ${{ matrix.node }}
          cache: 'npm'

      - uses: lvjiaxuan/release-deploy-publish-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          debug: true
          enableDeployBoolean: true
          deployScript: npm run ci"
