name: Update Dependencies

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * MON

jobs:
  update-deps:
    uses: lvjiaxuan/github-action-templates/.github/workflows/update-deps.yml@main
    with:
      email: 11309921+lvjiaxuan@users.noreply.github.com
